### ISSUE TITLE
glm-data for 2019

### ISSUE THREAD

**Issue by prakashvs613** [ucd-library/glm-lightning#2]
@qjhart, all files for datasets and flashes for 2019 are empty.

**Comment by qjhart** [comment]
@prakashvs613 there actually seemed to be issues wiith other years as well.  I've updsated those zip files, in that same location. https://drive.google.com/drive/folders/1SdcoDkv2X1kNDHl8Bi2OiNtn4rDbYzfC?usp=sharing

**Comment by prakashvs613** [comment]
This looks good. Thanks!
